Repro garbled JSON parse
Repro ijpt error:
```
Failed to start jira-node-1
java.lang.Exception: Failed to start jira-node-1
	at com.atlassian.performance.tools.awsinfrastructure.jira.DiagnosableStoppedNode.start(DiagnosableStoppedNode.kt:14)
	at com.atlassian.performance.tools.awsinfrastructure.api.jira.DataCenterFormula$provision$$inlined$map$lambda$1.call(DataCenterFormula.kt:299)
	at com.atlassian.performance.tools.awsinfrastructure.api.jira.DataCenterFormula$provision$$inlined$map$lambda$1.call(DataCenterFormula.kt:48)
	at com.atlassian.performance.tools.jvmtasks.api.TaskScope.task(TaskScope.kt:18)
	at com.atlassian.performance.tools.awsinfrastructure.api.jira.DataCenterFormula.provision(DataCenterFormula.kt:299)
	at com.atlassian.performance.tools.awsinfrastructure.api.jira.DataCenterFormula.provision(DataCenterFormula.kt:85)
	at com.atlassian.performance.tools.awsinfrastructure.api.InfrastructureFormula$provision$provisionJira$1.invoke(InfrastructureFormula.kt:77)
	at com.atlassian.performance.tools.awsinfrastructure.api.InfrastructureFormula$provision$provisionJira$1.invoke(InfrastructureFormula.kt:39)
	at com.atlassian.performance.tools.concurrency.api.TaskContextKt$sam$i$java_util_concurrent_Callable$0.call(TaskContext.kt)
	at com.atlassian.performance.tools.jvmtasks.api.TaskScope.task(TaskScope.kt:18)
	at com.atlassian.performance.tools.concurrency.api.TaskContextKt$submitWithLogContext$1.get(TaskContext.kt:25)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.Exception: Failed to start the Jira node.
	at com.atlassian.performance.tools.awsinfrastructure.jira.StandaloneStoppedNode.start(StandaloneStoppedNode.kt:71)
	at com.atlassian.performance.tools.awsinfrastructure.jira.DataCenterNodeFormula$provision$2.start(DataCenterNodeFormula.kt:30)
	at com.atlassian.performance.tools.awsinfrastructure.jira.DiagnosableStoppedNode.start(DiagnosableStoppedNode.kt:12)
	... 14 more
Caused by: javax.json.stream.JsonParsingException: Unexpected char 60 at (line no=1, column no=1, offset=0)
	at org.glassfish.json.JsonTokenizer.unexpectedChar(JsonTokenizer.java:601)
	at org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:418)
	at org.glassfish.json.JsonParserImpl$NoneContext.getNextEvent(JsonParserImpl.java:413)
	at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:363)
	at org.glassfish.json.JsonParserImpl$3.tryAdvance(JsonParserImpl.java:296)
	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:167)
	at com.atlassian.performance.tools.awsinfrastructure.jira.JiraStatus$Parser.parseResponse(JiraStatus.kt:25)
	at com.atlassian.performance.tools.awsinfrastructure.jira.StandaloneStoppedNode$waitForRunning$1.invoke(StandaloneStoppedNode.kt:122)
	at com.atlassian.performance.tools.awsinfrastructure.jira.StandaloneStoppedNode$waitForRunning$1.invoke(StandaloneStoppedNode.kt:23)
	at com.atlassian.performance.tools.awsinfrastructure.jira.StandaloneStoppedNode.pollJira(StandaloneStoppedNode.kt:199)
	at com.atlassian.performance.tools.awsinfrastructure.jira.StandaloneStoppedNode.waitForRunning(StandaloneStoppedNode.kt:115)
	at com.atlassian.performance.tools.awsinfrastructure.jira.StandaloneStoppedNode.start(StandaloneStoppedNode.kt:59)
	... 16 more
```

TDD: red