Fix JSON parser null state
Avoid:
```
java.lang.IllegalStateException: JsonParser#getObject() or JsonParser#getObjectStream() is valid only for START_OBJECT parser state. But current parser state is null
	at org.glassfish.json.JsonParserImpl.getObject(JsonParserImpl.java:171)
	at com.atlassian.performance.tools.awsinfrastructure.jira.JiraStatus$Parser.parseResponse(JiraStatus.kt:16)
	at com.atlassian.performance.tools.awsinfrastructure.jira.JiraStatusTest.shouldParseRunning(JiraStatusTest.kt:9)
```

TDD: green